production:
  api_key: your-api-key,
  lastfm_url: http://ws.audioscrobbler.com/2.0

development:
  api_key: your-api-key,
  lastfm_url: http://ws.audioscrobbler.com/2.0

test:
  api_key: your-api-key,
  lastfm_url: http://ws.audioscrobbler.com/2.0
